import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, paddingTop: 50 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 15,
    marginBottom: 10,
  },
  deleteSelectedBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: "rgba(255, 77, 77, 0.1)", // Light red tint
  },
  deleteSelectedText: {
    color: "#ff4d4d",
    fontWeight: "600",
    fontSize: 14,
  },
  headerTitle: { fontSize: 20, fontWeight: "700" },
  backBtn: { padding: 5 },
  selectAllRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    marginBottom: 10,
    justifyContent: "space-between",
  },
  cartItem: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 15,
    marginBottom: 12,
    padding: 12,
    borderRadius: 15,
    borderWidth: 1,
  },
  checkbox: { paddingRight: 12 },
  checkOuter: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    justifyContent: "center",
    alignItems: "center",
  },
  checkInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#ee4d2d",
  },
  itemImg: { width: 70, height: 70, backgroundColor: "#fff", borderRadius: 10 },
  itemInfo: { flex: 1, marginLeft: 15 },
  itemName: { fontSize: 15, fontWeight: "500" },
  itemPrice: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#ee4d2d",
    marginVertical: 4,
  },
  qtyRow: { flexDirection: "row", alignItems: "center", marginTop: 5 },
  qtyBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  qtyText: { marginHorizontal: 15, fontWeight: "bold" },
  deleteBtn: { padding: 8 },
  footer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    paddingBottom: 35,
  },
  totalLabel: { fontSize: 12, fontWeight: "600" },
  totalPrice: { fontSize: 20, fontWeight: "800" },
  checkoutBtn: {
    backgroundColor: "#ee4d2d",
    paddingHorizontal: 25,
    paddingVertical: 12,
    borderRadius: 12,
  },
  checkoutText: { color: "#fff", fontWeight: "bold", fontSize: 16 },
  emptyContainer: { alignItems: "center", paddingHorizontal: 40 },
  emptyTitle: { fontSize: 22, fontWeight: "bold", marginBottom: 10 },
  emptySub: {
    fontSize: 14,
    textAlign: "center",
    lineHeight: 22,
    marginBottom: 30,
  },
  shopBtn: { paddingHorizontal: 30, paddingVertical: 15, borderRadius: 15 },
  shopBtnText: { fontWeight: "bold", fontSize: 16 },
});
