import { StyleSheet } from "react-native";

export const Themes = {
  dark: {
    bg: "#121212",
    text: "#FFF",
    card: "#1E1E1E",
    qtyBg: "#333",
    qtyText: "#FFF",
    border: "#333",
    accent: "#fff",
    link: "#fff",
  },
  light: {
    bg: "#FFF",
    text: "#000",
    card: "#F9F9F9",
    qtyBg: "#F0F0F0",
    qtyText: "#000",
    border: "#EEE",
    accent: "#000",
    link: "#007AFF",
  },
};

export const styles = StyleSheet.create({
  container: { flex: 1, paddingHorizontal: 20, paddingTop: 60 },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
    height: 44,
  },
  headerSide: { width: 40, justifyContent: "center" },
  headerCenter: { flex: 1, alignItems: "center" },
  headerTitle: { fontSize: 18, fontWeight: "700" },
  itemRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    padding: 12,
    borderRadius: 16,
  },
  imgWrap: {
    width: 65,
    height: 65,
    borderRadius: 10,
    marginRight: 15,
    backgroundColor: "#fff",
    padding: 5,
    justifyContent: "center",
  },
  smallImg: { width: "100%", height: "100%" },
  infoCol: { flex: 1 },
  nameText: { fontSize: 15, fontWeight: "600", lineHeight: 20 },
  priceText: {
    color: "#ee4d2d",
    fontWeight: "700",
    fontSize: 14,
    marginTop: 4,
  },
  qtyControl: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  qtyChar: { fontSize: 18, fontWeight: "bold" },
  summaryFooter: {
    borderTopWidth: 1,
    paddingTop: 20,
    marginTop: 10,
    paddingBottom: 40,
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  totalLabel: { fontSize: 16, fontWeight: "500", opacity: 0.7 },
  grandTotal: { fontSize: 22, fontWeight: "800" },
  confirmBtn: { padding: 16, borderRadius: 14, alignItems: "center" },
  confirmBtnText: { fontWeight: "700", fontSize: 16 },
});
