import { Dimensions, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");
const CARD_WIDTH = (width - 40) / 2;

export const Themes = {
  dark: {
    bg: "#121212",
    text: "#fff",
    card: "#1E1E1E",
    input: "#2C2C2C",
    sub: "#aaa",
    border: "#333",
    icon: "#FFF",
    accent: "#ee4d2d",
  },
  light: {
    bg: "#F4F4F4",
    text: "#000",
    card: "#FFF",
    input: "#E8E8E8",
    sub: "#666",
    border: "#EEE",
    icon: "#1A1A1A",
    accent: "#ee4d2d",
  },
};

export const styles = StyleSheet.create({
  container: { flex: 1, paddingTop: 50 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 8,
  },
  searchContainer: {
    flex: 1,
    height: 44,
    borderRadius: 12,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
  },
  search: { height: "100%", fontSize: 15, flex: 1 },
  iconBtn: {
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  badge: {
    position: "absolute",
    right: 4,
    top: 4,
    backgroundColor: "#ee4d2d",
    borderRadius: 10,
    minWidth: 18,
    height: 18,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1,
  },
  badgeText: { color: "#fff", fontSize: 10, fontWeight: "800" },
  sortWrapper: { marginBottom: 10 },
  sortBar: { paddingHorizontal: 16, gap: 25, height: 40, alignItems: "center" },
  sortItem: {
    height: "100%",
    justifyContent: "center",
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
    paddingHorizontal: 4,
  },
  sortText: { fontSize: 13, fontWeight: "500" },
  boldText: { fontWeight: "700" },
  priceRow: { flexDirection: "row", alignItems: "center" },
  arrow: { fontSize: 12, marginLeft: 2 },
  listContent: { paddingBottom: 20 },
  emptyListContent: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 100,
  },
  columnWrapper: { justifyContent: "space-between", paddingHorizontal: 15 },
  productCard: {
    width: CARD_WIDTH,
    marginBottom: 15,
    borderRadius: 16,
    overflow: "hidden",
    elevation: 3,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  imageContainer: {
    width: "100%",
    height: 160,
    backgroundColor: "#fff",
    padding: 12,
  },
  img: { width: "100%", height: "100%" },
  cardContent: { padding: 12 },
  productName: { fontSize: 14, fontWeight: "500", height: 36, lineHeight: 18 },
  productPrice: {
    fontSize: 17,
    color: "#ee4d2d",
    fontWeight: "700",
    marginVertical: 2,
  },
  ratingRow: { flexDirection: "row", alignItems: "center", marginTop: 4 },
  starText: { fontSize: 11, color: "#f1c40f", fontWeight: "600" },
  soldText: { fontSize: 11 },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "flex-end",
  },
  modalContent: {
    height: "92%",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  modalTitleHeader: { fontSize: 17, fontWeight: "700" },
  modalScroll: { paddingBottom: 130 },
  largeImg: {
    width: "100%",
    height: 300,
    backgroundColor: "#fff",
    borderRadius: 20,
  },
  modalTitle: { fontSize: 22, fontWeight: "800", marginTop: 20 },
  modalMetaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 12,
  },
  modalPrice: { fontSize: 26, color: "#ee4d2d", fontWeight: "900" },
  divider: {
    height: 1,
    backgroundColor: "rgba(150, 150, 150, 0.1)",
    marginVertical: 20,
  },
  sectionTitle: { fontSize: 16, fontWeight: "700", marginBottom: 10 },
  descText: { fontSize: 15, lineHeight: 23 },
  bottomBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 16,
    borderTopWidth: 1,
    paddingBottom: 34,
  },
  qtyContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  qtyBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  qtyText: { fontWeight: "800", marginHorizontal: 20 },
  actionBtns: { flexDirection: "row", gap: 12 },
  addBtn: {
    flex: 1,
    backgroundColor: "#ffb916",
    height: 50,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  buyBtn: {
    flex: 1,
    backgroundColor: "#ee4d2d",
    height: 50,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  btnText: { color: "#fff", fontWeight: "700", fontSize: 16 },
});
