import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, paddingTop: 50 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 15,
    marginBottom: 15,
    gap: 10,
  },
  searchContainer: {
    flex: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  search: { height: 40, fontSize: 14 },
  iconBtn: { padding: 5, position: "relative" },
  badge: {
    position: "absolute",
    right: 0,
    top: 0,
    backgroundColor: "#ee4d2d",
    borderRadius: 8,
    width: 16,
    height: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  badgeText: { color: "#fff", fontSize: 9, fontWeight: "bold" },
  columnWrapper: { justifyContent: "space-between", paddingHorizontal: 10 },
  productCard: {
    width: "48%",
    marginBottom: 12,
    borderRadius: 8,
    overflow: "hidden",
    elevation: 2,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  imageContainer: {
    width: "100%",
    height: 150,
    backgroundColor: "#fff",
    padding: 10,
  },
  img: { width: "100%", height: "100%" },
  cardContent: { padding: 8 },
  productName: { fontSize: 13, fontWeight: "400", height: 34, lineHeight: 17 },
  productPrice: {
    fontSize: 16,
    color: "#ee4d2d",
    fontWeight: "bold",
    marginVertical: 4,
  },
  ratingRow: { flexDirection: "row", alignItems: "center" },
  starText: { fontSize: 10, color: "#f1c40f" },
  soldText: { fontSize: 10 },

  emptyContainer: { alignItems: "center", paddingHorizontal: 40 },
  emptyTitle: { fontSize: 18, fontWeight: "bold", marginBottom: 5 },
  emptySub: { fontSize: 14, textAlign: "center", lineHeight: 20 },
  resetBtn: { marginTop: 15, padding: 10 },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    height: "90%",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
  },
  modalTitleHeader: { fontSize: 16, fontWeight: "600" },
  largeImg: {
    width: "100%",
    height: 280,
    backgroundColor: "#fff",
    borderRadius: 10,
  },
  modalTitle: { fontSize: 19, fontWeight: "bold", marginTop: 15 },
  modalMetaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
  },
  modalPrice: { fontSize: 24, color: "#ee4d2d", fontWeight: "bold" },
  divider: { height: 1, backgroundColor: "#eee", marginVertical: 15 },
  sectionTitle: { fontSize: 15, fontWeight: "bold", marginBottom: 8 },
  descText: { fontSize: 14, lineHeight: 20 },
  reviewCard: { marginBottom: 12 },
  reviewHeader: { flexDirection: "row", justifyContent: "space-between" },
  reviewUser: { fontWeight: "600", fontSize: 13 },
  reviewDate: { fontSize: 11, color: "#999" },
  reviewComment: { fontSize: 13, marginTop: 2 },
  bottomBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 15,
    borderTopWidth: 1,
    paddingBottom: 30,
  },
  qtyContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 15,
  },
  qtyBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#ccc",
    justifyContent: "center",
    alignItems: "center",
  },
  actionBtns: { flexDirection: "row", gap: 10 },
  addBtn: {
    flex: 1,
    backgroundColor: "#ffb916",
    padding: 14,
    borderRadius: 8,
    alignItems: "center",
  },
  buyBtn: {
    flex: 1,
    backgroundColor: "#ee4d2d",
    padding: 14,
    borderRadius: 8,
    alignItems: "center",
  },
  btnText: { color: "#fff", fontWeight: "bold", fontSize: 15 },
});
